### PR TITLE
Moved registry instance to options

### PR DESCRIPTION
**Pull request by tudurom**
This fixed a weird race condition that I was experiencing in random conditions.

### CODE REVIEW

**Comment by asim** [comment]
Whats the race condition?

**Comment by tudurom** [comment]
It seems that even without my changes the registry is still _not_ changed from the command line
After inserting a debug message, running my program like this

```
./api-srv --registry mdns
```

Shows up that the registry that it's using is still the consul registry.

Also, my changes make my code work, so it's definitely not ignoring the new registry.

**Comment by tudurom** [comment]
Oh my yes, the address is specified in an env var while the registry is specified in code. So that's why it defaults to consul. That's why it happens only in docker compose, because I had to set the address in a var.

So... it shouldn't default to consul. It should just leave the registry as is.

**Comment by tudurom** [comment]
And how do I do that?

**Comment by tudurom** [comment]
Thanks for the help!

**Pull request closed without merging**
